"""Add encryption mode and encrypted DEK to agent_state

Revision ID: 3c2745bf165a
Revises:
Create Date: 2026-02-05 23:56:16.650204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c2745bf165a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("encrypted_tarball", sa.LargeBinary(), nullable=True),
        sa.Column("tarball_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "encryption_mode",
            sa.Enum("ZERO_TRUST", "BACKGROUND", name="encryptionmode"),
            server_default="ZERO_TRUST",
            nullable=False,
        ),
        sa.Column("encrypted_dek", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "agent_name", name="uq_agent_states_user_agent"),
    )
    op.create_index("idx_agent_states_user", "agent_states", ["user_id"], unique=False)
    op.create_index(op.f("ix_agent_states_user_id"), "agent_states", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_states_user_id"), table_name="agent_states")
    op.drop_index("idx_agent_states_user", table_name="agent_states")
    op.drop_table("agent_states")
    # ### end Alembic commands ###
